import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'generated-index',
        title: 'Installation Guide',
        description: 'Learn how to install and configure PCode',
        slug: '/installation',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'installation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Feature Guides',
      link: {
        type: 'generated-index',
        title: 'Feature Guides',
        description: 'Explore PCode features and capabilities',
        slug: '/feature-guides',
      },
      items: [
        {
          type: 'category',
          label: 'Session Management',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'Session Management',
            description: 'Learn how to manage and use PCode sessions',
            slug: '/feature-guides/session-management',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'feature-guides/session-management',
            },
          ],
        },
        {
          type: 'category',
          label: 'Conversation Features',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'Conversation Features',
            description: 'Learn about PCode conversation and messaging features',
            slug: '/feature-guides/conversation',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'feature-guides/conversation',
            },
          ],
        },
        {
          type: 'category',
          label: 'Project Management',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'Project Management',
            description: 'Learn how to create and manage projects',
            slug: '/feature-guides/project-management',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'feature-guides/project-management',
            },
          ],
        },
        {
          type: 'category',
          label: 'OpenSpec Proposals',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'OpenSpec Proposals',
            description: 'Learn how to use OpenSpec to manage proposals',
            slug: '/feature-guides/openspec',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'feature-guides/openspec',
            },
          ],
        },
        {
          type: 'category',
          label: 'Statistics & Achievements',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'Statistics & Achievements',
            description: 'View usage statistics and unlock achievements',
            slug: '/feature-guides/statistics',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'feature-guides/statistics',
            },
            {
              type: 'autogenerated',
              dirName: 'feature-guides/achievements',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      link: {
        type: 'generated-index',
        title: 'Configuration',
        description: 'Configure PCode to suit your needs',
        slug: '/configuration',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'configuration',
        },
      ],
    },
    {
      type: 'category',
      label: 'User Guide',
      link: {
        type: 'generated-index',
        title: 'User Guide',
        description: 'Learn how to use PCode effectively',
        slug: '/user-guide',
      },
      items: [
        {
          type: 'category',
          label: 'Appearance',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'Appearance',
            description: 'Customize PCode appearance',
            slug: '/user-guide/appearance',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'user-guide/appearance',
            },
          ],
        },
        {
          type: 'category',
          label: 'Settings',
          collapsible: true,
          collapsed: false,
          link: {
            type: 'generated-index',
            title: 'Settings',
            description: 'Manage PCode settings',
            slug: '/user-guide/settings',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'user-guide/settings',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
