import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Quick Start',
      link: {
        type: 'generated-index',
        title: 'Quick Start',
        description: 'Get started with PCode quickly',
        slug: '/quick-start',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'quick-start',
        },
      ],
    },
    {
      type: 'category',
      label: '相关软件安装',
      link: {
        type: 'generated-index',
        title: '相关软件安装',
        description: '安装和配置 PCode 所需的相关软件',
        slug: '/related-software-installation',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'related-software-installation',
        },
      ],
    },
  ],
};

export default sidebars;
